Deterministic account derivation with seed
AleoHQ/aleo pull request #270
Opened 2022-04-15 15:55 UTC by piotr-roslaniec

## Motivation

With these changes, WASM-bindings users can take advantage of RNG bundled with SDK to generate accounts deterministically. 

## Test Plan

Tested by modifying the existing test suite.

## Related PRs

(No related PRs)

2022-04-21 21:52 UTC, collinc97 requested changes
Thanks for the PR!
It is close to what we want but with a few changes.

2022-04-21 21:52 UTC, collinc97 commented on wasm/src/account/account.rs
> +    pub fn from_seed(seed: &[u8]) -> Self {
This method can be shortened. In addition, you should use `ChaChaRng`.
```rust
AccountNative::new(&mut ChaChaRng::seed_from_u64(seed))
```
Please see our implementation in the CLI of this repository for an example.

2022-08-17 08:37 UTC, howardwu commented
@piotr-roslaniec checking in here. Is this PR still relevant?

2022-08-19 14:06 UTC, piotr-roslaniec commented
@howardwu Yes, I still need a way to generate `Account` (or `PrivateKey`) in a deterministic way.

2022-10-06 23:47 UTC, closed without merging