Aleo Development Server
AleoHQ/aleo pull request #512
Opened 2023-03-24 01:47 UTC by iamalwaysuncomfortable

## Motivation

Most developers working building applications on Aleo are working with javascript or typescript environments. Unfortunately Aleo tooling mostly consists of rust libraries or cli tools which force developers to build somewhat painful bridges such as OS pipes within cloud containers in order to interact with the Aleo Blockchain.

The Aleo development server is meant to provide a simple REST API for use in local development or cloud-based applications.

## Test Plan
* Integration tests will be written against the server once its running that validate its creating successful executions and deployments.

2023-04-06 01:03 UTC, collinc97 requested changes
First pass over `rust/develop/` server.
Looking great - just a few english nits.

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/README.md
> +Once started, the he endpoints have the following options. All requests should be sent as a POST request with a json body.
nit
```suggestion
Once started, the endpoints have the following options. All requests should be sent as a POST request with a json body.
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/README.md
> +* `private_key`: Optional private key of the user who is deploying the program
Make "Required" and "Optional" parameters consistent.
@iamalwaysuncomfortable if you have a preferred way to write these that is better than this suggestion that is fine.
```suggestion
* `fee`: Required fee to be paid for the program deployment
* `private_key`: Optional private key of the user who is deploying the program
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/README.md
> +* `returns`: The transaction_id of the deployment transaction if successful
```suggestion
* `returns`: The transaction ID of the deployment transaction if successful
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/README.md
> +* `program_id` The program_id of the program to be executed (e.g. hello.aleo)
```suggestion
* `program_id` The program ID of the program to be executed (e.g. hello.aleo)
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/README.md
> +* `fee` Optional Fee to be paid for the transfer, specify 0 for no fee
```suggestion
* `fee` Optional fee to be paid for the transfer, specify 0 for no fee
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/README.md
> +* `returns`: The transaction_id of the execution transaction if successful
```suggestion
* `returns`: The transaction ID of the execution transaction if successful
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/README.md
> +@returns {string | Error} The transaction_id of the execution transaction if successful
```suggestion
@returns {string | Error} The transaction ID of the execution transaction if successful
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/src/lib.rs
> +//! * `fee`: Fee to be paid for the program deployment (REQUIRED)
```suggestion
//! * `fee`: Required fee to be paid for the program deployment
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/src/lib.rs
> +//! * `returns`: The transaction_id of the deployment transaction if successful
```suggestion
//! * `returns`: The transaction ID of the deployment transaction if successful
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/src/lib.rs
> +//! * `program_id` The program_id of the program to be executed (e.g. hello.aleo)
```suggestion
//! * `program_id` The program ID of the program to be executed (e.g. hello.aleo)
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/src/lib.rs
> +//! * `fee` Optional Fee to be paid for the transfer, specify 0 for no fee
```suggestion
//! * `fee` Optional fee to be paid for the transfer, specify 0 for no fee
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/src/lib.rs
> +//! * `returns`: The transaction_id of the execution transaction if successful
```suggestion
//! * `returns`: The transaction ID of the execution transaction if successful
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/src/lib.rs
> +//! * `fee` Optional Fee to be paid for the transfer, specify 0 for no fee
```suggestion
//! * `fee` Optional fee to be paid for the transfer, specify 0 for no fee
```

2023-04-06 01:03 UTC, collinc97 commented on rust/develop/src/lib.rs
> +//! @returns {string | Error} The transaction_id of the execution transaction if successful
```suggestion
//! @returns {string | Error} The transaction ID of the execution transaction if successful
```

2023-04-12 05:31 UTC, collinc97 requested changes
This functionality is vital to making Aleo web-ready.
Thanks for the hard work @iamalwaysuncomfortable!

I think the naming between `AleoNetworkClient` and `DevelopmentClient` can be improved.
In my opinion, they should both be `AleoNetworkClient` and `AleoDevelopmentClient`  
or `NetworkClient` and `DevelopmentClient`  
or maybe something more clear.
Let's discuss during the next sync.

Code-wise this PR looks good!

2023-04-12 05:31 UTC, collinc97 commented on sdk/src/node_connection.js
> + * let local_connection = new NodeConnection("http://localhost:3030");
```suggestion
 * let local_connection = new AleoNetworkClient("http://localhost:3030");
```

2023-04-12 05:31 UTC, collinc97 commented on sdk/src/node_connection.js
> + * let public_connection = new NodeConnection("https://vm.aleo.org/api");
```suggestion
 * let public_connection = new AleoNetworkClient("https://vm.aleo.org/api");
```

2023-04-12 05:31 UTC, collinc97 commented on sdk/src/node_connection.js
Should this file be renamed to Aleo network client?

2023-04-13 00:25 UTC, iamalwaysuncomfortable commented on sdk/src/node_connection.js
> + * let public_connection = new NodeConnection("https://vm.aleo.org/api");
Good suggestion, done!

2023-04-13 00:25 UTC, iamalwaysuncomfortable commented on sdk/src/node_connection.js
Yes, done!

2023-04-13 00:26 UTC, iamalwaysuncomfortable commented on sdk/src/node_connection.js
> + * let local_connection = new NodeConnection("http://localhost:3030");
Absolutely agree

2023-04-13 17:51 UTC, collinc97 approved these changes

2023-04-14 18:19 UTC, merged