Add typescript template
AleoHQ/aleo pull request #785
Opened 2023-10-19 22:13 UTC by CalebCurry

## Motivation

Typescript good

## Test Plan

(Write your test plan here)

## Related PRs

(Link your related PRs here)

2023-10-20 16:11 UTC, onetrickwolf requested changes
Looks good I think there's some stuff we could iterate on but I am fine to merge this and iterate so it doesn't get too behind. I would just mainly rename this as `template-react-ts` and make it a variant instead of it's own category.

2023-10-20 16:11 UTC, onetrickwolf commented on create-aleo-app/src/index.ts
> +    name: "react-typescript",
This should probably be a variant under React not it's own thing. Would take a look at how vite does it: https://github.com/vitejs/vite/blob/main/packages/create-vite/src/index.ts#L90

2023-10-20 16:11 UTC, onetrickwolf commented on create-aleo-app/template-react-typescript/package.json
> +    "@aleohq/wasm": "^0.6.2",
wasm isn't needed in package.json it's included in the SDK

2023-10-20 16:11 UTC, onetrickwolf commented on create-aleo-app/template-react-typescript/package.json
> +    "@types/babel__generator": "^7.6.6",
these types should probably be in dev dependencies

2023-10-20 16:11 UTC, onetrickwolf commented on create-aleo-app/template-react-typescript/package.json
> +    "@types/node": "^20.8.7",
same here

2023-10-20 16:11 UTC, onetrickwolf commented on create-aleo-app/template-react-typescript/.eslintrc.cjs
> +module.exports = {
would maybe configure this a little more for typescript but fine for now we can iterate

2023-10-20 16:11 UTC, onetrickwolf commented on create-aleo-app/template-react-typescript/tsconfig.json
> +  "include": ["build.config.ts", "src", "__tests__", "src/custom.d.ts"],
don't think there's a build.config.ts

2023-10-26 14:56 UTC, iamalwaysuncomfortable commented
@CalebCurry is there any plan to finish this template?

2023-11-03 15:00 UTC, onetrickwolf approved these changes

2023-11-04 01:39 UTC, merged