Migrating to ProvableHQ and Provable URLs
AleoHQ/aleo pull request #893
Opened 2024-07-03 19:57 UTC by onetrickwolf

## Motivation

Still a work in progress. Will move out of draft when ready for review but happy to have comments before that.

Migrate Aleo URLs and packages to Provable. Keep Aleo references when referring to the Aleo network, this change is just to reflect moving the SDK to Provable Inc. (the company).

Example of distinction: Things referring to the company like `@aleohq` with be migrating `@provablehq` but things referring to the network like `create-aleo-app` will remain since it's referring to the Aleo network and creating an app for the Aleo network.

## Test Plan

- [ ] SDK published and working links and references
- [ ] WASM published and working links and references
- [ ] Aleo.tools properly redirects to Provable.tools and all links updated
- [ ] `create-aleo-app` examples work (this may be a stretch goal since some were previously not working)
- [ ] All CICD checks pass
- [ ] Website compiles and deploys properly

2024-07-03 21:32 UTC, onetrickwolf commented
https://www.npmjs.com/package/@provablehq/wasm and https://www.npmjs.com/package/@provablehq/sdk published. Going to test then probably increment and republish before flagging aleohq packages as deprecated.

2024-07-04 01:38 UTC, Pauan requested changes

2024-07-04 01:38 UTC, Pauan commented on .github/ISSUE_TEMPLATE.md
> +## 👉 [Please follow one of these issue templates](https://github.com/Provablehq/sdk/issues/new/choose) 👈
```suggestion
## 👉 [Please follow one of these issue templates](https://github.com/ProvableHQ/sdk/issues/new/choose) 👈
```

2024-07-04 01:38 UTC, Pauan commented on .github/PULL_REQUEST_TEMPLATE.md
> +    please take some time to update the docs at https://github.com/Provablehq/sdk,
```suggestion
    please take some time to update the docs at https://github.com/ProvableHQ/sdk,
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +    <a href="https://circleci.com/gh/Provablehq/sdk"><img src="https://circleci.com/gh/Provablehq/sdk.svg?style=svg"></a>
```suggestion
    <a href="https://circleci.com/gh/ProvableHQ/sdk"><img src="https://circleci.com/gh/ProvableHQ/sdk.svg?style=svg"></a>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +    <a href="https://github.com/Provablehq/sdk#%EF%B8%8F-contributors"><img src="https://img.shields.io/badge/contributors-23-ee8449"/></a>
```suggestion
    <a href="https://github.com/ProvableHQ/sdk#%EF%B8%8F-contributors"><img src="https://img.shields.io/badge/contributors-23-ee8449"/></a>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +The [Aleo SDK](https://github.com/Provablehq/sdk) provides tools for building zero knowledge applications. It consists of
```suggestion
The [Aleo SDK](https://github.com/ProvableHQ/sdk) provides tools for building zero knowledge applications. It consists of
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +Start here with the [Aleo SDK Readme](https://github.com/Provablehq/sdk/tree/testnet3/sdk#readme) to get started building your
```suggestion
Start here with the [Aleo SDK Readme](https://github.com/ProvableHQ/sdk#readme) to get started building your 
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +#### Source: [`sdk/sdk`](https://github.com/Provablehq/sdk/tree/testnet3/sdk)
```suggestion
#### Source: [`sdk/sdk`](https://github.com/ProvableHQ/sdk/tree/testnet3/sdk)
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +#### Source: [`sdk/create-aleo-app`](https://github.com/Provablehq/sdk/tree/testnet3/create-aleo-app)
```suggestion
#### Source: [`sdk/create-aleo-app`](https://github.com/ProvableHQ/sdk/tree/testnet3/create-aleo-app)
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +Source: [`sdk/wasm`](https://github.com/Provablehq/sdk/tree/testnet3/wasm)
```suggestion
Source: [`sdk/wasm`](https://github.com/ProvableHQ/sdk/tree/testnet3/wasm)
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +#### [SDK Readme](https://github.com/Provablehq/sdk/tree/testnet3/sdk#readme)
```suggestion
#### [SDK Readme](https://github.com/ProvableHQ/sdk/tree/testnet3/sdk#readme)
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +#### [Aleo Wasm Readme](https://github.com/Provablehq/sdk/tree/testnet3/wasm#readme)
```suggestion
#### [Aleo Wasm Readme](https://github.com/ProvableHQ/sdk/tree/testnet3/wasm#readme)
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/iamalwaysuncomfortable"><img src="https://avatars.githubusercontent.com/u/26438809?v=4?s=100" width="100px;" alt="Mike
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/iamalwaysuncomfortable"><img src="https://avatars.githubusercontent.com/u/26438809?v=4?s=100" width="100px;" alt="Mike Turner"/><br /><sub><b>Mike Turner</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=iamalwaysuncomfortable" title="Code">💻</a> <a href="#maintenance-iamalwaysuncomfortable" title="Maintenance">🚧</a> <a href="#question-iamalwaysuncomfortable" title="Answering Questions">💬</a> <a href="https://github.com/ProvableHQ/sdk/pulls?q=is%3Apr+reviewed-by%3Aiamalwaysuncomfortable" title="Reviewed Pull Requests">👀</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/onetrickwolf"><img src="https://avatars.githubusercontent.com/u/13836477?v=4?s=100" width="100px;" alt="Brent C"/><br
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/onetrickwolf"><img src="https://avatars.githubusercontent.com/u/13836477?v=4?s=100" width="100px;" alt="Brent C"/><br /><sub><b>Brent C</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=onetrickwolf" title="Code">💻</a> <a href="#maintenance-onetrickwolf" title="Maintenance">🚧</a> <a href="#question-onetrickwolf" title="Answering Questions">💬</a> <a href="https://github.com/ProvableHQ/sdk/pulls?q=is%3Apr+reviewed-by%3Aonetrickwolf" title="Reviewed Pull Requests">👀</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/collinc97"><img src="https://avatars.githubusercontent.com/u/16715212?v=4?s=100" width="100px;" alt="Collin Chin"/><br
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/collinc97"><img src="https://avatars.githubusercontent.com/u/16715212?v=4?s=100" width="100px;" alt="Collin Chin"/><br /><sub><b>Collin Chin</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=collinc97" title="Code">💻</a> <a href="#maintenance-collinc97" title="Maintenance">🚧</a> <a href="#question-collinc97" title="Answering Questions">💬</a> <a href="https://github.com/ProvableHQ/sdk/pulls?q=is%3Apr+reviewed-by%3Acollinc97" title="Reviewed Pull Requests">👀</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/howardwu"><img src="https://avatars.githubusercontent.com/u/9260812?v=4?s=100" width="100px;" alt="Howard Wu"/><br /><
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/howardwu"><img src="https://avatars.githubusercontent.com/u/9260812?v=4?s=100" width="100px;" alt="Howard Wu"/><br /><sub><b>Howard Wu</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=howardwu" title="Code">💻</a> <a href="#ideas-howardwu" title="Ideas, Planning, & Feedback">🤔</a> <a href="#research-howardwu" title="Research">🔬</a> <a href="https://github.com/ProvableHQ/sdk/pulls?q=is%3Apr+reviewed-by%3Ahowardwu" title="Reviewed Pull Requests">👀</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/raychu86"><img src="https://avatars.githubusercontent.com/u/14917648?v=4?s=100" width="100px;" alt="Raymond Chu"/><br
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/raychu86"><img src="https://avatars.githubusercontent.com/u/14917648?v=4?s=100" width="100px;" alt="Raymond Chu"/><br /><sub><b>Raymond Chu</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=raychu86" title="Code">💻</a> <a href="#ideas-raychu86" title="Ideas, Planning, & Feedback">🤔</a> <a href="#research-raychu86" title="Research">🔬</a> <a href="https://github.com/ProvableHQ/sdk/pulls?q=is%3Apr+reviewed-by%3Araychu86" title="Reviewed Pull Requests">👀</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/d0cd"><img src="https://avatars.githubusercontent.com/u/23022326?v=4?s=100" width="100px;" alt="d0cd"/><br /><sub><b>d
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/d0cd"><img src="https://avatars.githubusercontent.com/u/23022326?v=4?s=100" width="100px;" alt="d0cd"/><br /><sub><b>d0cd</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=d0cd" title="Code">💻</a> <a href="#ideas-d0cd" title="Ideas, Planning, & Feedback">🤔</a> <a href="#research-d0cd" title="Research">🔬</a> <a href="https://github.com/ProvableHQ/sdk/pulls?q=is%3Apr+reviewed-by%3Ad0cd" title="Reviewed Pull Requests">👀</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://alessandrocoglio.info"><img src="https://avatars.githubusercontent.com/u/2409151?v=4?s=100" width="100px;" alt="Alessandro Coglio
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://alessandrocoglio.info"><img src="https://avatars.githubusercontent.com/u/2409151?v=4?s=100" width="100px;" alt="Alessandro Coglio"/><br /><sub><b>Alessandro Coglio</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=acoglio" title="Documentation">📖</a> <a href="#research-acoglio" title="Research">🔬</a> <a href="https://github.com/ProvableHQ/sdk/pulls?q=is%3Apr+reviewed-by%3Aacoglio" title="Reviewed Pull Requests">👀</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/aharshbe"><img src="https://avatars.githubusercontent.com/u/17191728?v=4?s=100" width="100px;" alt="a h"/><br /><sub><
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/aharshbe"><img src="https://avatars.githubusercontent.com/u/17191728?v=4?s=100" width="100px;" alt="a h"/><br /><sub><b>a h</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=aharshbe" title="Code">💻</a> <a href="https://github.com/ProvableHQ/sdk/commits?author=aharshbe" title="Documentation">📖</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/adiprinzio"><img src="https://avatars.githubusercontent.com/u/32148721?v=4?s=100" width="100px;" alt="Anthony DiPrinzi
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/adiprinzio"><img src="https://avatars.githubusercontent.com/u/32148721?v=4?s=100" width="100px;" alt="Anthony DiPrinzio"/><br /><sub><b>Anthony DiPrinzio</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=adiprinzio" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/amousa11"><img src="https://avatars.githubusercontent.com/u/12452142?v=4?s=100" width="100px;" alt="Ali Mousa"/><br />
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/amousa11"><img src="https://avatars.githubusercontent.com/u/12452142?v=4?s=100" width="100px;" alt="Ali Mousa"/><br /><sub><b>Ali Mousa</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=amousa11" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/ilitteri"><img src="https://avatars.githubusercontent.com/u/67517699?v=4?s=100" width="100px;" alt="Ivan Litteri"/><br
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/ilitteri"><img src="https://avatars.githubusercontent.com/u/67517699?v=4?s=100" width="100px;" alt="Ivan Litteri"/><br /><sub><b>Ivan Litteri</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=ilitteri" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://www.linkedin.com/in/ignacio-avecilla-39386a191/"><img src="https://avatars.githubusercontent.com/u/63374472?v=4?s=100" width="100
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://www.linkedin.com/in/ignacio-avecilla-39386a191/"><img src="https://avatars.githubusercontent.com/u/63374472?v=4?s=100" width="100px;" alt="Nacho Avecilla"/><br /><sub><b>Nacho Avecilla</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=IAvecilla" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/ljedrz"><img src="https://avatars.githubusercontent.com/u/3750347?v=4?s=100" width="100px;" alt="ljedrz"/><br /><sub><
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/ljedrz"><img src="https://avatars.githubusercontent.com/u/3750347?v=4?s=100" width="100px;" alt="ljedrz"/><br /><sub><b>ljedrz</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=ljedrz" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://facundoolano.github.io/"><img src="https://avatars.githubusercontent.com/u/1040941?v=4?s=100" width="100px;" alt="Facundo Olano"/
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://facundoolano.github.io/"><img src="https://avatars.githubusercontent.com/u/1040941?v=4?s=100" width="100px;" alt="Facundo Olano"/><br /><sub><b>Facundo Olano</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=facundoolano" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/ncontinanza"><img src="https://avatars.githubusercontent.com/u/17294394?v=4?s=100" width="100px;" alt="Nicolas Contina
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/ncontinanza"><img src="https://avatars.githubusercontent.com/u/17294394?v=4?s=100" width="100px;" alt="Nicolas Continanza"/><br /><sub><b>Nicolas Continanza</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=ncontinanza" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/fulltimemike"><img src="https://avatars.githubusercontent.com/u/32080293?v=4?s=100" width="100px;" alt="Mike"/><br /><
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/fulltimemike"><img src="https://avatars.githubusercontent.com/u/32080293?v=4?s=100" width="100px;" alt="Mike"/><br /><sub><b>Mike</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=fulltimemike" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/jrchatruc"><img src="https://avatars.githubusercontent.com/u/49622509?v=4?s=100" width="100px;" alt="Javier Rodríguez
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/jrchatruc"><img src="https://avatars.githubusercontent.com/u/49622509?v=4?s=100" width="100px;" alt="Javier Rodríguez Chatruc"/><br /><sub><b>Javier Rodríguez Chatruc</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=jrchatruc" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/pablodeymo"><img src="https://avatars.githubusercontent.com/u/12279806?v=4?s=100" width="100px;" alt="Pablo Deymonnaz"
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/pablodeymo"><img src="https://avatars.githubusercontent.com/u/12279806?v=4?s=100" width="100px;" alt="Pablo Deymonnaz"/><br /><sub><b>Pablo Deymonnaz</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=pablodeymo" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/spartucus"><img src="https://avatars.githubusercontent.com/u/6071887?v=4?s=100" width="100px;" alt="Bob Niu"/><br /><s
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/spartucus"><img src="https://avatars.githubusercontent.com/u/6071887?v=4?s=100" width="100px;" alt="Bob Niu"/><br /><sub><b>Bob Niu</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=spartucus" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/dev-sptg"><img src="https://avatars.githubusercontent.com/u/585251?v=4?s=100" width="100px;" alt="sptg"/><br /><sub><b
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/dev-sptg"><img src="https://avatars.githubusercontent.com/u/585251?v=4?s=100" width="100px;" alt="sptg"/><br /><sub><b>sptg</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=dev-sptg" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/Hamzakh777"><img src="https://avatars.githubusercontent.com/u/40059557?v=4?s=100" width="100px;" alt="Hamza Khchichine
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/Hamzakh777"><img src="https://avatars.githubusercontent.com/u/40059557?v=4?s=100" width="100px;" alt="Hamza Khchichine"/><br /><sub><b>Hamza Khchichine</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=Hamzakh777" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/KendrickDrews"><img src="https://avatars.githubusercontent.com/u/15710081?v=4s=100" width="100px;" alt="Kendrick"/><br
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/KendrickDrews"><img src="https://avatars.githubusercontent.com/u/15710081?v=4s=100" width="100px;" alt="Kendrick"/><br /><sub><b>Kendrick</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=KendrickDrews" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://github.com/features/security"><img src="https://avatars.githubusercontent.com/u/27347476?v=4?s=100" width="100px;" alt="Dependabo
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/features/security"><img src="https://avatars.githubusercontent.com/u/27347476?v=4?s=100" width="100px;" alt="Dependabot"/><br /><sub><b>Dependabot</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=dependabot" title="Code">💻</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on README.md
> +      <td align="center" valign="top" width="14.28%"><a href="https://allcontributors.org/"><img src="https://avatars.githubusercontent.com/u/46410174?v=4?s=100" width="100px;" alt="All Contributors"
```suggestion
      <td align="center" valign="top" width="14.28%"><a href="https://allcontributors.org/"><img src="https://avatars.githubusercontent.com/u/46410174?v=4?s=100" width="100px;" alt="All Contributors"/><br /><sub><b>All Contributors</b></sub></a><br /><a href="https://github.com/ProvableHQ/sdk/commits?author=all-contributors" title="Documentation">📖</a></td>
```

2024-07-04 01:38 UTC, Pauan commented on create-aleo-app/template-react-leo/README.md
> +[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/Provablehq/sdk/tree/testnet3/create-aleo-app/template-react-leo)
```suggestion
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/ProvableHQ/sdk/tree/testnet3/create-aleo-app/template-react-leo)
```

2024-07-04 01:38 UTC, Pauan commented on create-aleo-app/template-react-leo/README.md
> +3. Follow instructions to install Leo here: https://github.com/Provablehq/leo
```suggestion
3. Follow instructions to install Leo here: https://github.com/ProvableHQ/leo
```

2024-07-04 01:38 UTC, Pauan commented on create-aleo-app/template-react-leo/install.sh
> +  git clone https://github.com/Provablehq/leo "$INSTALL_DIR"
```suggestion
  git clone https://github.com/ProvableHQ/leo "$INSTALL_DIR"
```

2024-07-04 01:38 UTC, Pauan commented on create-aleo-app/template-react-ts/README.md
> +[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/Provablehq/sdk/tree/testnet3/create-aleo-app/template-react)
```suggestion
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/ProvableHQ/sdk/tree/testnet3/create-aleo-app/template-react)
```

2024-07-04 01:38 UTC, Pauan commented on create-aleo-app/template-react-ts/README.md
> +3. Follow instructions to install Leo here: https://github.com/Provablehq/leo
```suggestion
3. Follow instructions to install Leo here: https://github.com/ProvableHQ/leo
```

2024-07-04 01:38 UTC, Pauan commented on create-aleo-app/template-react-ts/install.sh
> +  git clone https://github.com/Provablehq/leo "$INSTALL_DIR"
```suggestion
  git clone https://github.com/ProvableHQ/leo "$INSTALL_DIR"
```

2024-07-04 01:38 UTC, Pauan commented on website/README.md
> +-   Follow [SDK Build Guide](https://github.com/Provablehq/sdk#2-build-guide) to get Rust installed
```suggestion
-   Follow [SDK Build Guide](https://github.com/ProvableHQ/sdk#2-build-guide) to get Rust installed
```

2024-07-04 01:38 UTC, Pauan commented on website/src/main.jsx
> +                            <a href="https://github.com/Provablehq/sdk">
```suggestion
                            <a href="https://github.com/ProvableHQ/sdk">
```

2024-07-08 23:09 UTC, Pauan approved these changes
It looks like there's some weird spurious test failures.

But otherwise this LGTM

2024-07-09 19:20 UTC, onetrickwolf commented
> It looks like there's some weird spurious test failures.
> 
> But otherwise this LGTM

Yeah @Pauan the failures were from tests hitting the network and checking for accounts that existed in testnet3 but not in testnet-beta. I talked to @iamalwaysuncomfortable about this and we probably shouldn't have unit tests that are hitting the network. We can just set up a stub or something and if we really want to check the network maybe make it an e2e that runs on merge as a sanity check. But yeah I don't really want test flake from network availability. I disabled the test for now.

2024-07-09 21:45 UTC, merged

2024-07-09 21:48 UTC, onetrickwolf commented
@christianwwwwwwww is going to fix the `create-aleo-app` examples in another PR, was a bit too much to fit in this one.