Adding in support for mainnet
AleoHQ/aleo pull request #897
Opened 2024-07-12 02:59 UTC by Pauan

This PR allows users to use either testnet or mainnet (or both).

The user imports whichever network they want to use:

```js
import * as sdk from "@provablehq/sdk/testnet.js";
```

```js
import * as sdk from "@provablehq/sdk/mainnet.js";
```

2024-07-16 13:30 UTC, iamalwaysuncomfortable commented on wasm/build.js
> +                    "--features", `browser,${network}`,
What are the consequences on this on node.js support?

2024-07-16 13:30 UTC, iamalwaysuncomfortable commented on wasm/src/types/networks/mod.rs
> +pub use testnet::*;
This is a good way to approach it.

2024-07-16 15:32 UTC, Pauan commented on wasm/build.js
> +                    "--features", `browser,${network}`,
There shouldn't be any consequences, everything should work the same in Node as it does right now.

This is just adding in a new `testnet` / `mainnet` feature flag, the `testnet` flag is identical to the current behavior.

2024-08-06 22:13 UTC, Pauan commented
I added in some end-to-end tests under the `sdk/e2e` folder.

Right now I just copied the Node template, so it's just doing a basic "hello world".

But over time we can add more e2e tests and flesh them out.

2024-08-06 22:15 UTC, Pauan commented
Also as discussed in Slack, I got rid of Jest and replaced it with Mocha + Chai + Sinon. The unit tests work so much better now.

2024-08-06 22:23 UTC, Pauan commented
The PR is ready for review now, but it can't be merged until after mainnet launches, because it relies upon mainnet URLs that just don't exist right now.

After mainnet launches, we will re-run all of the tests until they're all green!

2024-09-23 20:37 UTC, jaketarnow requested changes

2024-09-23 20:37 UTC, jaketarnow commented on README.md
> +    <a href="https://developer.provable.com"> <img alt="Website" src="https://img.shields.io/badge/Developer_Docs-online-blue"></a>
This can remain as `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on README.md
> +#### [API Documentation](https://developer.provable.com/sdk/typescript/overview)
This can remain as `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on README.md
> +be found on the [Aleo Developer Docs](https://developer.provable.com/sdk/typescript/overview) page.
This can remain as `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on website/src/pages/TermsOfUse.jsx
>                  provided by Provable Inc., a Delaware corporation (including its
Do not update anything on `/website/src/pages/TermsOfUse`

2024-09-23 20:37 UTC, jaketarnow commented on create-leo-app/template-react-leo/README.md
> +if you are unfamiliar: https://developer.provable.com/testnet/getting_started/deploy_execute_demo
This can remain as `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on create-leo-app/template-react-ts/README.md
> +if you are unfamiliar: https://developer.provable.com/testnet/getting_started/deploy_execute_demo
This can remain as `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on sdk/README.md
> +    <a href="https://developer.provable.com"> <img alt="Website" src="https://img.shields.io/badge/Developer_Docs-online-blue"></a>
This can remain as `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on sdk/README.md
> +them. Under the hood it uses cryptographic code compiled from [SnarkVM](https://developer.provable.com/aleo) into WebAssembly
This can remain as `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on wasm/src/lib.rs
> +//! More information on these concepts can be found at the [Aleo Developer Hub](https://developer.provable.com/concepts).
Use `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on website/src/pages/Homepage.jsx
> +                    to="https://developer.provable.com/sdk/"
Use `developer.aleo.org`

2024-09-23 20:37 UTC, jaketarnow commented on .github/ISSUE_TEMPLATE/bug.md
> +
Keep as `security@aleo.org`

2024-09-24 01:09 UTC, iamalwaysuncomfortable commented
One final comment from my end is to update all SnarkVM dependencies to rev `3d42aa0` (i.e. the latest stable rev)

2024-09-24 01:10 UTC, iamalwaysuncomfortable reviewed
One final comment from my end is to update all SnarkVM dependencies to rev 3d42aa0 (i.e. the latest stable rev). This ensures the correct `Network` trait constants are present in the SDK!

2024-09-24 20:31 UTC, jaketarnow approved these changes
LGTM

2024-09-24 20:47 UTC, merged