Removes extra caller input from transfer_public
AleoHQ/aleo pull request #905
Opened 2024-07-26 11:39 UTC by Zack-Xb

## Motivation
Executing a public transfer using the program manager `transfer` function fails as the `transfer_public` option in `wasm/src/programs/manager/transfer.rs` has 3 inputs not 2 as required by the program function as you can see here https://explorer.aleo.org/program/credits.aleo. Removing the first parameter should resolve this, and also the `caller` address parameter is not required for the transfer function.

## Test Plan
Re compile the rust to wasm and test out executing `ProgramManager.transfer({amount}, {recipient}, {transfer_type}, {fee})`.

2024-07-29 21:54 UTC, jaketarnow approved these changes
Thanks for this @Zack-Xb! 
lgtm

2024-07-29 21:58 UTC, christianwwwwwwww approved these changes
LGTM 🤓

2024-08-01 19:10 UTC, iamalwaysuncomfortable requested changes
These do not include the changes to the javascript end of the SDK nor the Provable.tools website. Those signatures should also be updated - #907 addresses these.

2025-03-06 01:40 UTC, closed without merging

2025-03-06 01:40 UTC, iamalwaysuncomfortable commented
Changes have been addressed in succeeding PRs, thanks for the callout