[Feature] Add Field, Group, Scalar, Plaintext, Ciphertext, Transitions, and Transactions to JS SDK.
AleoHQ/aleo pull request #948
Opened 2024-12-10 15:02 UTC by iamalwaysuncomfortable

## Motivation

Several feature requests have requested that the ability to the following be added to the SDK.
* Be able to do Field, Group, and Scalar arithmetic and be generally able to work with those types 
* Easily peer into Transaction and Transition data and associated inputs and outputs
* Work with Ciphertexts and get items from `Struct` and `Array` types

This PR adds these types to the SDK with the ability to turn them into JavaScript/TypeScript objects for convenient extraction of data into a front or backend app as well as api methods that allow these new types to be directly instantiated when calling api endpoints.

It also provides several new typescript types that allow typescript users to work with the JS representation of these objects.

Once this PR is approved, it will constitute the release candidate for the next major version bump.

## Test Plan

This PR adds the following unit tests for the new objects:
* Field, Scalar, and Group arithmetic.
* Conversion of Transitions and Transactions to JS objects.

## Related PRs

#944 - this PR adds the exports of SnarkVM types to `wasm` and provides code that

2024-12-10 20:10 UTC, Pauan requested changes
Some minor nits, but generally looks good.

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/confirmed_transaction.ts
>  export type ConfirmedTransaction = {
For objects, it's better to use an `interface` instead of `type`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/deploy.ts
> +export type DeploymentMetadata = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/executionJSON.ts
> +export type ExecutionJSON = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/functionObject.ts
> +export type FunctionObject = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/input/inputJSON.ts
> +export type InputJSON = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/input/inputObject.ts
> +export type InputObject = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/input/inputObject.ts
> +import { Plaintext } from "@provablehq/wasm/mainnet.js";
Why is this importing `mainnet`?

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/input/inputObject.ts
> +import { Ciphertext, Field } from "@provablehq/wasm";
This should be importing `../../wasm` instead of `@provablehq/wasm`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/output/outputJSON.ts
> +export type OutputJSON = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/output/outputObject.ts
> +export type OutputObject = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/output/outputObject.ts
> +import { Field, Ciphertext, Plaintext } from "@provablehq/wasm";
This should import `../../wasm` instead.

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/transaction/transactionJSON.ts
> +export type TransactionJSON = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/transaction/transactionSummary.ts
> +export type TransactionSummary = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/transition/transitionJSON.ts
> +export type TransitionJSON = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/transition/transitionObject.ts
> +export type TransitionObject = {
Same as above, this should be an `interface`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/models/transition/transitionObject.ts
> +import { Field, Group } from "@provablehq/wasm";
This should import `../../wasm`

2024-12-10 20:10 UTC, Pauan commented on sdk/src/network-client.ts
> +          .reduce<Array<Transaction>>((acc, transaction) => {
Why is this using `reduce` instead of `map`?

2024-12-10 20:10 UTC, Pauan commented on sdk/src/network-client.ts
> +          .reduce<Array<Transaction>>((acc, transaction) => {
Similarly, why is this using `reduce`?

2024-12-10 20:10 UTC, Pauan commented on sdk/tests/key-provider.test.ts
> +        // it('should not fetch invalid transfer keys', async () => {
I think it's cleaner to use `describe.skip` or `it.skip` to skip the tests, instead of commenting it out.

2024-12-10 20:10 UTC, Pauan commented on sdk/tests/network-client.test.ts
> +import { Plaintext, Transition } from "@provablehq/wasm";
This should be importing from `../src/node` instead of `@provablehq/wasm`.

2024-12-10 20:10 UTC, Pauan commented on sdk/tests/network-client.test.ts
> +import { TransitionObject } from "../src/models/transition/transitionObject";
This should probably also be importing from `../src/node`

2024-12-10 20:10 UTC, Pauan commented on sdk/tests/network-client.test.ts
> +import { PlaintextObject } from "../src/models/plaintext/plaintext";
This should probably also be importing from `../src/node`

2025-01-14 23:37 UTC, Pauan commented
Since the docs are being auto-generated by the `build:sdk-docs` script, shouldn't the `.html` files be added into `.gitignore`?

2025-01-15 15:25 UTC, Pauan approved these changes
LGTM

2025-01-15 16:04 UTC, iamalwaysuncomfortable commented
> Since the docs are being auto-generated by the `build:sdk-docs` script, shouldn't the `.html` files be added into `.gitignore`?

In theory yes, but in practice when users, especially ones new to the protocol or who aren't great at JS arrive here they don't think to run that. I've found users reaching for the HTML docs immediately and getting use out of it, so this is why it's done currently. We should however replace this with a very prominent link to these documents online. That doesn't exist yet, but I'll talk to @jaketarnow to see if we can make it so.

2025-01-16 20:42 UTC, jaketarnow approved these changes
LGTM

2025-01-16 20:57 UTC, Pauan requested changes
One minor thing and this'll be good to go.

2025-01-16 20:57 UTC, Pauan commented on sdk/src/network-client.ts
> +      return Plaintext.fromString(JSON.parse(value));
Why is this using `JSON.parse` instead of `parseJSON`?

2025-01-16 20:57 UTC, Pauan commented on sdk/src/utils.ts
> +        if (Number.isInteger(value) && value.length > 15) {
We should fix this for real.

But in the meantime, if we want to go with the "conditionally returns bigint if it's too big" logic, then it should be like this:

```js
if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
```

2025-01-16 21:33 UTC, iamalwaysuncomfortable commented on sdk/src/network-client.ts
> +      return Plaintext.fromString(JSON.parse(value));
Because it doesn't decode into the rust object using parseJSON.

2025-01-16 21:33 UTC, iamalwaysuncomfortable commented on sdk/src/utils.ts
> +        if (Number.isInteger(value) && value.length > 15) {
This was an oversight, thanks for catching it.

2025-01-16 23:10 UTC, Pauan approved these changes

2025-01-16 23:10 UTC, Pauan commented on sdk/tests/network-client.test.ts
> +                expect(transactions[0].index).equal(BigInt(0));
You don't need to make any changes, but just for future reference you can use `0n` for bigint literals, which makes them a lot more convenient to use.

2025-01-17 00:09 UTC, iamalwaysuncomfortable commented on sdk/tests/network-client.test.ts
> +                expect(transactions[0].index).equal(BigInt(0));
That's a good tip, thanks.

2025-01-24 01:09 UTC, merged